// Code generated by Kitex v0.9.1. DO NOT EDIT.

package messageservice

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	message "github.com/jizizr/goligoli/server/kitex_gen/message"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	AddMessage(ctx context.Context, req *message.AddMessageRequest, callOptions ...callopt.Option) (err error)
	GetMessage(ctx context.Context, req *message.GetMessageRequest, callOptions ...callopt.Option) (r *message.GetMessageResponse, err error)
	GetHistoryMessages(ctx context.Context, req *message.GetHistoryMessagesRequest, callOptions ...callopt.Option) (r *message.GetHistoryMessagesResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfoForClient(), options...)
	if err != nil {
		return nil, err
	}
	return &kMessageServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kMessageServiceClient struct {
	*kClient
}

func (p *kMessageServiceClient) AddMessage(ctx context.Context, req *message.AddMessageRequest, callOptions ...callopt.Option) (err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.AddMessage(ctx, req)
}

func (p *kMessageServiceClient) GetMessage(ctx context.Context, req *message.GetMessageRequest, callOptions ...callopt.Option) (r *message.GetMessageResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetMessage(ctx, req)
}

func (p *kMessageServiceClient) GetHistoryMessages(ctx context.Context, req *message.GetHistoryMessagesRequest, callOptions ...callopt.Option) (r *message.GetHistoryMessagesResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetHistoryMessages(ctx, req)
}
