// Code generated by hertz generator.

package api

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _loginMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _registerMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _bulletMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _gethistorybulletsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _sendbulletMw() []app.HandlerFunc {
	// your code...
	return nil
}
