// Code generated by Kitex v0.9.1. DO NOT EDIT.

package pushservice

import (
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	push "github.com/jizizr/goligoli/server/kitex_gen/push"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"PushBullet": kitex.NewMethodInfo(
		pushBulletHandler,
		newPushServicePushBulletArgs,
		newPushServicePushBulletResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	pushServiceServiceInfo                = NewServiceInfo()
	pushServiceServiceInfoForClient       = NewServiceInfoForClient()
	pushServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return pushServiceServiceInfo
}

// for client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return pushServiceServiceInfoForStreamClient
}

// for stream client
func serviceInfoForClient() *kitex.ServiceInfo {
	return pushServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "PushService"
	handlerType := (*push.PushService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "push",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.9.1",
		Extra:           extra,
	}
	return svcInfo
}

func pushBulletHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*push.PushServicePushBulletArgs)

	err := handler.(push.PushService).PushBullet(ctx, realArg.Req)
	if err != nil {
		return err
	}

	return nil
}
func newPushServicePushBulletArgs() interface{} {
	return push.NewPushServicePushBulletArgs()
}

func newPushServicePushBulletResult() interface{} {
	return push.NewPushServicePushBulletResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) PushBullet(ctx context.Context, req *push.PushBulletRequest) (err error) {
	var _args push.PushServicePushBulletArgs
	_args.Req = req
	var _result push.PushServicePushBulletResult
	if err = p.c.Call(ctx, "PushBullet", &_args, &_result); err != nil {
		return
	}
	return nil
}
