// Code generated by thriftgo (0.3.12). DO NOT EDIT.

package bullet

import (
	"context"
	"fmt"
	"github.com/apache/thrift/lib/go/thrift"
	"github.com/jizizr/goligoli/server/kitex_gen/base"
)

type AddBulletRequest struct {
	Bullet *base.Bullet `thrift:"bullet,1" frugal:"1,default,base.Bullet" json:"bullet"`
}

func NewAddBulletRequest() *AddBulletRequest {
	return &AddBulletRequest{}
}

func (p *AddBulletRequest) InitDefault() {
	*p = AddBulletRequest{}
}

var AddBulletRequest_Bullet_DEFAULT *base.Bullet

func (p *AddBulletRequest) GetBullet() (v *base.Bullet) {
	if !p.IsSetBullet() {
		return AddBulletRequest_Bullet_DEFAULT
	}
	return p.Bullet
}
func (p *AddBulletRequest) SetBullet(val *base.Bullet) {
	p.Bullet = val
}

var fieldIDToName_AddBulletRequest = map[int16]string{
	1: "bullet",
}

func (p *AddBulletRequest) IsSetBullet() bool {
	return p.Bullet != nil
}

func (p *AddBulletRequest) Read(iprot thrift.TProtocol) (err error) {

	var fieldTypeId thrift.TType
	var fieldId int16

	if _, err = iprot.ReadStructBegin(); err != nil {
		goto ReadStructBeginError
	}

	for {
		_, fieldTypeId, fieldId, err = iprot.ReadFieldBegin()
		if err != nil {
			goto ReadFieldBeginError
		}
		if fieldTypeId == thrift.STOP {
			break
		}

		switch fieldId {
		case 1:
			if fieldTypeId == thrift.STRUCT {
				if err = p.ReadField1(iprot); err != nil {
					goto ReadFieldError
				}
			} else if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		default:
			if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		}
		if err = iprot.ReadFieldEnd(); err != nil {
			goto ReadFieldEndError
		}
	}
	if err = iprot.ReadStructEnd(); err != nil {
		goto ReadStructEndError
	}

	return nil
ReadStructBeginError:
	return thrift.PrependError(fmt.Sprintf("%T read struct begin error: ", p), err)
ReadFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T read field %d begin error: ", p, fieldId), err)
ReadFieldError:
	return thrift.PrependError(fmt.Sprintf("%T read field %d '%s' error: ", p, fieldId, fieldIDToName_AddBulletRequest[fieldId]), err)
SkipFieldError:
	return thrift.PrependError(fmt.Sprintf("%T field %d skip type %d error: ", p, fieldId, fieldTypeId), err)

ReadFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T read field end error", p), err)
ReadStructEndError:
	return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
}

func (p *AddBulletRequest) ReadField1(iprot thrift.TProtocol) error {
	_field := base.NewBullet()
	if err := _field.Read(iprot); err != nil {
		return err
	}
	p.Bullet = _field
	return nil
}

func (p *AddBulletRequest) Write(oprot thrift.TProtocol) (err error) {
	var fieldId int16
	if err = oprot.WriteStructBegin("AddBulletRequest"); err != nil {
		goto WriteStructBeginError
	}
	if p != nil {
		if err = p.writeField1(oprot); err != nil {
			fieldId = 1
			goto WriteFieldError
		}
	}
	if err = oprot.WriteFieldStop(); err != nil {
		goto WriteFieldStopError
	}
	if err = oprot.WriteStructEnd(); err != nil {
		goto WriteStructEndError
	}
	return nil
WriteStructBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
WriteFieldError:
	return thrift.PrependError(fmt.Sprintf("%T write field %d error: ", p, fieldId), err)
WriteFieldStopError:
	return thrift.PrependError(fmt.Sprintf("%T write field stop error: ", p), err)
WriteStructEndError:
	return thrift.PrependError(fmt.Sprintf("%T write struct end error: ", p), err)
}

func (p *AddBulletRequest) writeField1(oprot thrift.TProtocol) (err error) {
	if err = oprot.WriteFieldBegin("bullet", thrift.STRUCT, 1); err != nil {
		goto WriteFieldBeginError
	}
	if err := p.Bullet.Write(oprot); err != nil {
		return err
	}
	if err = oprot.WriteFieldEnd(); err != nil {
		goto WriteFieldEndError
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 1 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 1 end error: ", p), err)
}

func (p *AddBulletRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AddBulletRequest(%+v)", *p)

}

func (p *AddBulletRequest) DeepEqual(ano *AddBulletRequest) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field1DeepEqual(ano.Bullet) {
		return false
	}
	return true
}

func (p *AddBulletRequest) Field1DeepEqual(src *base.Bullet) bool {

	if !p.Bullet.DeepEqual(src) {
		return false
	}
	return true
}

type GetBulletRequest struct {
	BulletId int64 `thrift:"bullet_id,1" frugal:"1,default,i64" json:"bullet_id"`
}

func NewGetBulletRequest() *GetBulletRequest {
	return &GetBulletRequest{}
}

func (p *GetBulletRequest) InitDefault() {
	*p = GetBulletRequest{}
}

func (p *GetBulletRequest) GetBulletId() (v int64) {
	return p.BulletId
}
func (p *GetBulletRequest) SetBulletId(val int64) {
	p.BulletId = val
}

var fieldIDToName_GetBulletRequest = map[int16]string{
	1: "bullet_id",
}

func (p *GetBulletRequest) Read(iprot thrift.TProtocol) (err error) {

	var fieldTypeId thrift.TType
	var fieldId int16

	if _, err = iprot.ReadStructBegin(); err != nil {
		goto ReadStructBeginError
	}

	for {
		_, fieldTypeId, fieldId, err = iprot.ReadFieldBegin()
		if err != nil {
			goto ReadFieldBeginError
		}
		if fieldTypeId == thrift.STOP {
			break
		}

		switch fieldId {
		case 1:
			if fieldTypeId == thrift.I64 {
				if err = p.ReadField1(iprot); err != nil {
					goto ReadFieldError
				}
			} else if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		default:
			if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		}
		if err = iprot.ReadFieldEnd(); err != nil {
			goto ReadFieldEndError
		}
	}
	if err = iprot.ReadStructEnd(); err != nil {
		goto ReadStructEndError
	}

	return nil
ReadStructBeginError:
	return thrift.PrependError(fmt.Sprintf("%T read struct begin error: ", p), err)
ReadFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T read field %d begin error: ", p, fieldId), err)
ReadFieldError:
	return thrift.PrependError(fmt.Sprintf("%T read field %d '%s' error: ", p, fieldId, fieldIDToName_GetBulletRequest[fieldId]), err)
SkipFieldError:
	return thrift.PrependError(fmt.Sprintf("%T field %d skip type %d error: ", p, fieldId, fieldTypeId), err)

ReadFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T read field end error", p), err)
ReadStructEndError:
	return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
}

func (p *GetBulletRequest) ReadField1(iprot thrift.TProtocol) error {

	var _field int64
	if v, err := iprot.ReadI64(); err != nil {
		return err
	} else {
		_field = v
	}
	p.BulletId = _field
	return nil
}

func (p *GetBulletRequest) Write(oprot thrift.TProtocol) (err error) {
	var fieldId int16
	if err = oprot.WriteStructBegin("GetBulletRequest"); err != nil {
		goto WriteStructBeginError
	}
	if p != nil {
		if err = p.writeField1(oprot); err != nil {
			fieldId = 1
			goto WriteFieldError
		}
	}
	if err = oprot.WriteFieldStop(); err != nil {
		goto WriteFieldStopError
	}
	if err = oprot.WriteStructEnd(); err != nil {
		goto WriteStructEndError
	}
	return nil
WriteStructBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
WriteFieldError:
	return thrift.PrependError(fmt.Sprintf("%T write field %d error: ", p, fieldId), err)
WriteFieldStopError:
	return thrift.PrependError(fmt.Sprintf("%T write field stop error: ", p), err)
WriteStructEndError:
	return thrift.PrependError(fmt.Sprintf("%T write struct end error: ", p), err)
}

func (p *GetBulletRequest) writeField1(oprot thrift.TProtocol) (err error) {
	if err = oprot.WriteFieldBegin("bullet_id", thrift.I64, 1); err != nil {
		goto WriteFieldBeginError
	}
	if err := oprot.WriteI64(p.BulletId); err != nil {
		return err
	}
	if err = oprot.WriteFieldEnd(); err != nil {
		goto WriteFieldEndError
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 1 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 1 end error: ", p), err)
}

func (p *GetBulletRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetBulletRequest(%+v)", *p)

}

func (p *GetBulletRequest) DeepEqual(ano *GetBulletRequest) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field1DeepEqual(ano.BulletId) {
		return false
	}
	return true
}

func (p *GetBulletRequest) Field1DeepEqual(src int64) bool {

	if p.BulletId != src {
		return false
	}
	return true
}

type GetBulletResponse struct {
	Bullet *base.Bullet `thrift:"bullet,1,optional" frugal:"1,optional,base.Bullet" json:"bullet,omitempty"`
}

func NewGetBulletResponse() *GetBulletResponse {
	return &GetBulletResponse{}
}

func (p *GetBulletResponse) InitDefault() {
	*p = GetBulletResponse{}
}

var GetBulletResponse_Bullet_DEFAULT *base.Bullet

func (p *GetBulletResponse) GetBullet() (v *base.Bullet) {
	if !p.IsSetBullet() {
		return GetBulletResponse_Bullet_DEFAULT
	}
	return p.Bullet
}
func (p *GetBulletResponse) SetBullet(val *base.Bullet) {
	p.Bullet = val
}

var fieldIDToName_GetBulletResponse = map[int16]string{
	1: "bullet",
}

func (p *GetBulletResponse) IsSetBullet() bool {
	return p.Bullet != nil
}

func (p *GetBulletResponse) Read(iprot thrift.TProtocol) (err error) {

	var fieldTypeId thrift.TType
	var fieldId int16

	if _, err = iprot.ReadStructBegin(); err != nil {
		goto ReadStructBeginError
	}

	for {
		_, fieldTypeId, fieldId, err = iprot.ReadFieldBegin()
		if err != nil {
			goto ReadFieldBeginError
		}
		if fieldTypeId == thrift.STOP {
			break
		}

		switch fieldId {
		case 1:
			if fieldTypeId == thrift.STRUCT {
				if err = p.ReadField1(iprot); err != nil {
					goto ReadFieldError
				}
			} else if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		default:
			if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		}
		if err = iprot.ReadFieldEnd(); err != nil {
			goto ReadFieldEndError
		}
	}
	if err = iprot.ReadStructEnd(); err != nil {
		goto ReadStructEndError
	}

	return nil
ReadStructBeginError:
	return thrift.PrependError(fmt.Sprintf("%T read struct begin error: ", p), err)
ReadFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T read field %d begin error: ", p, fieldId), err)
ReadFieldError:
	return thrift.PrependError(fmt.Sprintf("%T read field %d '%s' error: ", p, fieldId, fieldIDToName_GetBulletResponse[fieldId]), err)
SkipFieldError:
	return thrift.PrependError(fmt.Sprintf("%T field %d skip type %d error: ", p, fieldId, fieldTypeId), err)

ReadFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T read field end error", p), err)
ReadStructEndError:
	return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
}

func (p *GetBulletResponse) ReadField1(iprot thrift.TProtocol) error {
	_field := base.NewBullet()
	if err := _field.Read(iprot); err != nil {
		return err
	}
	p.Bullet = _field
	return nil
}

func (p *GetBulletResponse) Write(oprot thrift.TProtocol) (err error) {
	var fieldId int16
	if err = oprot.WriteStructBegin("GetBulletResponse"); err != nil {
		goto WriteStructBeginError
	}
	if p != nil {
		if err = p.writeField1(oprot); err != nil {
			fieldId = 1
			goto WriteFieldError
		}
	}
	if err = oprot.WriteFieldStop(); err != nil {
		goto WriteFieldStopError
	}
	if err = oprot.WriteStructEnd(); err != nil {
		goto WriteStructEndError
	}
	return nil
WriteStructBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
WriteFieldError:
	return thrift.PrependError(fmt.Sprintf("%T write field %d error: ", p, fieldId), err)
WriteFieldStopError:
	return thrift.PrependError(fmt.Sprintf("%T write field stop error: ", p), err)
WriteStructEndError:
	return thrift.PrependError(fmt.Sprintf("%T write struct end error: ", p), err)
}

func (p *GetBulletResponse) writeField1(oprot thrift.TProtocol) (err error) {
	if p.IsSetBullet() {
		if err = oprot.WriteFieldBegin("bullet", thrift.STRUCT, 1); err != nil {
			goto WriteFieldBeginError
		}
		if err := p.Bullet.Write(oprot); err != nil {
			return err
		}
		if err = oprot.WriteFieldEnd(); err != nil {
			goto WriteFieldEndError
		}
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 1 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 1 end error: ", p), err)
}

func (p *GetBulletResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetBulletResponse(%+v)", *p)

}

func (p *GetBulletResponse) DeepEqual(ano *GetBulletResponse) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field1DeepEqual(ano.Bullet) {
		return false
	}
	return true
}

func (p *GetBulletResponse) Field1DeepEqual(src *base.Bullet) bool {

	if !p.Bullet.DeepEqual(src) {
		return false
	}
	return true
}

type GetHistoryBulletsRequest struct {
	LiveId    int64 `thrift:"live_id,1" frugal:"1,default,i64" json:"live_id"`
	StartTime int64 `thrift:"start_time,2" frugal:"2,default,i64" json:"start_time"`
	Offset    int64 `thrift:"offset,3" frugal:"3,default,i64" json:"offset"`
}

func NewGetHistoryBulletsRequest() *GetHistoryBulletsRequest {
	return &GetHistoryBulletsRequest{}
}

func (p *GetHistoryBulletsRequest) InitDefault() {
	*p = GetHistoryBulletsRequest{}
}

func (p *GetHistoryBulletsRequest) GetLiveId() (v int64) {
	return p.LiveId
}

func (p *GetHistoryBulletsRequest) GetStartTime() (v int64) {
	return p.StartTime
}

func (p *GetHistoryBulletsRequest) GetOffset() (v int64) {
	return p.Offset
}
func (p *GetHistoryBulletsRequest) SetLiveId(val int64) {
	p.LiveId = val
}
func (p *GetHistoryBulletsRequest) SetStartTime(val int64) {
	p.StartTime = val
}
func (p *GetHistoryBulletsRequest) SetOffset(val int64) {
	p.Offset = val
}

var fieldIDToName_GetHistoryBulletsRequest = map[int16]string{
	1: "live_id",
	2: "start_time",
	3: "offset",
}

func (p *GetHistoryBulletsRequest) Read(iprot thrift.TProtocol) (err error) {

	var fieldTypeId thrift.TType
	var fieldId int16

	if _, err = iprot.ReadStructBegin(); err != nil {
		goto ReadStructBeginError
	}

	for {
		_, fieldTypeId, fieldId, err = iprot.ReadFieldBegin()
		if err != nil {
			goto ReadFieldBeginError
		}
		if fieldTypeId == thrift.STOP {
			break
		}

		switch fieldId {
		case 1:
			if fieldTypeId == thrift.I64 {
				if err = p.ReadField1(iprot); err != nil {
					goto ReadFieldError
				}
			} else if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		case 2:
			if fieldTypeId == thrift.I64 {
				if err = p.ReadField2(iprot); err != nil {
					goto ReadFieldError
				}
			} else if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		case 3:
			if fieldTypeId == thrift.I64 {
				if err = p.ReadField3(iprot); err != nil {
					goto ReadFieldError
				}
			} else if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		default:
			if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		}
		if err = iprot.ReadFieldEnd(); err != nil {
			goto ReadFieldEndError
		}
	}
	if err = iprot.ReadStructEnd(); err != nil {
		goto ReadStructEndError
	}

	return nil
ReadStructBeginError:
	return thrift.PrependError(fmt.Sprintf("%T read struct begin error: ", p), err)
ReadFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T read field %d begin error: ", p, fieldId), err)
ReadFieldError:
	return thrift.PrependError(fmt.Sprintf("%T read field %d '%s' error: ", p, fieldId, fieldIDToName_GetHistoryBulletsRequest[fieldId]), err)
SkipFieldError:
	return thrift.PrependError(fmt.Sprintf("%T field %d skip type %d error: ", p, fieldId, fieldTypeId), err)

ReadFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T read field end error", p), err)
ReadStructEndError:
	return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
}

func (p *GetHistoryBulletsRequest) ReadField1(iprot thrift.TProtocol) error {

	var _field int64
	if v, err := iprot.ReadI64(); err != nil {
		return err
	} else {
		_field = v
	}
	p.LiveId = _field
	return nil
}
func (p *GetHistoryBulletsRequest) ReadField2(iprot thrift.TProtocol) error {

	var _field int64
	if v, err := iprot.ReadI64(); err != nil {
		return err
	} else {
		_field = v
	}
	p.StartTime = _field
	return nil
}
func (p *GetHistoryBulletsRequest) ReadField3(iprot thrift.TProtocol) error {

	var _field int64
	if v, err := iprot.ReadI64(); err != nil {
		return err
	} else {
		_field = v
	}
	p.Offset = _field
	return nil
}

func (p *GetHistoryBulletsRequest) Write(oprot thrift.TProtocol) (err error) {
	var fieldId int16
	if err = oprot.WriteStructBegin("GetHistoryBulletsRequest"); err != nil {
		goto WriteStructBeginError
	}
	if p != nil {
		if err = p.writeField1(oprot); err != nil {
			fieldId = 1
			goto WriteFieldError
		}
		if err = p.writeField2(oprot); err != nil {
			fieldId = 2
			goto WriteFieldError
		}
		if err = p.writeField3(oprot); err != nil {
			fieldId = 3
			goto WriteFieldError
		}
	}
	if err = oprot.WriteFieldStop(); err != nil {
		goto WriteFieldStopError
	}
	if err = oprot.WriteStructEnd(); err != nil {
		goto WriteStructEndError
	}
	return nil
WriteStructBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
WriteFieldError:
	return thrift.PrependError(fmt.Sprintf("%T write field %d error: ", p, fieldId), err)
WriteFieldStopError:
	return thrift.PrependError(fmt.Sprintf("%T write field stop error: ", p), err)
WriteStructEndError:
	return thrift.PrependError(fmt.Sprintf("%T write struct end error: ", p), err)
}

func (p *GetHistoryBulletsRequest) writeField1(oprot thrift.TProtocol) (err error) {
	if err = oprot.WriteFieldBegin("live_id", thrift.I64, 1); err != nil {
		goto WriteFieldBeginError
	}
	if err := oprot.WriteI64(p.LiveId); err != nil {
		return err
	}
	if err = oprot.WriteFieldEnd(); err != nil {
		goto WriteFieldEndError
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 1 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 1 end error: ", p), err)
}

func (p *GetHistoryBulletsRequest) writeField2(oprot thrift.TProtocol) (err error) {
	if err = oprot.WriteFieldBegin("start_time", thrift.I64, 2); err != nil {
		goto WriteFieldBeginError
	}
	if err := oprot.WriteI64(p.StartTime); err != nil {
		return err
	}
	if err = oprot.WriteFieldEnd(); err != nil {
		goto WriteFieldEndError
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 2 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 2 end error: ", p), err)
}

func (p *GetHistoryBulletsRequest) writeField3(oprot thrift.TProtocol) (err error) {
	if err = oprot.WriteFieldBegin("offset", thrift.I64, 3); err != nil {
		goto WriteFieldBeginError
	}
	if err := oprot.WriteI64(p.Offset); err != nil {
		return err
	}
	if err = oprot.WriteFieldEnd(); err != nil {
		goto WriteFieldEndError
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 3 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 3 end error: ", p), err)
}

func (p *GetHistoryBulletsRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetHistoryBulletsRequest(%+v)", *p)

}

func (p *GetHistoryBulletsRequest) DeepEqual(ano *GetHistoryBulletsRequest) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field1DeepEqual(ano.LiveId) {
		return false
	}
	if !p.Field2DeepEqual(ano.StartTime) {
		return false
	}
	if !p.Field3DeepEqual(ano.Offset) {
		return false
	}
	return true
}

func (p *GetHistoryBulletsRequest) Field1DeepEqual(src int64) bool {

	if p.LiveId != src {
		return false
	}
	return true
}
func (p *GetHistoryBulletsRequest) Field2DeepEqual(src int64) bool {

	if p.StartTime != src {
		return false
	}
	return true
}
func (p *GetHistoryBulletsRequest) Field3DeepEqual(src int64) bool {

	if p.Offset != src {
		return false
	}
	return true
}

type GetHistoryBulletsResponse struct {
	Bullets []*base.Bullet `thrift:"bullets,1" frugal:"1,default,list<base.Bullet>" json:"bullets"`
}

func NewGetHistoryBulletsResponse() *GetHistoryBulletsResponse {
	return &GetHistoryBulletsResponse{}
}

func (p *GetHistoryBulletsResponse) InitDefault() {
	*p = GetHistoryBulletsResponse{}
}

func (p *GetHistoryBulletsResponse) GetBullets() (v []*base.Bullet) {
	return p.Bullets
}
func (p *GetHistoryBulletsResponse) SetBullets(val []*base.Bullet) {
	p.Bullets = val
}

var fieldIDToName_GetHistoryBulletsResponse = map[int16]string{
	1: "bullets",
}

func (p *GetHistoryBulletsResponse) Read(iprot thrift.TProtocol) (err error) {

	var fieldTypeId thrift.TType
	var fieldId int16

	if _, err = iprot.ReadStructBegin(); err != nil {
		goto ReadStructBeginError
	}

	for {
		_, fieldTypeId, fieldId, err = iprot.ReadFieldBegin()
		if err != nil {
			goto ReadFieldBeginError
		}
		if fieldTypeId == thrift.STOP {
			break
		}

		switch fieldId {
		case 1:
			if fieldTypeId == thrift.LIST {
				if err = p.ReadField1(iprot); err != nil {
					goto ReadFieldError
				}
			} else if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		default:
			if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		}
		if err = iprot.ReadFieldEnd(); err != nil {
			goto ReadFieldEndError
		}
	}
	if err = iprot.ReadStructEnd(); err != nil {
		goto ReadStructEndError
	}

	return nil
ReadStructBeginError:
	return thrift.PrependError(fmt.Sprintf("%T read struct begin error: ", p), err)
ReadFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T read field %d begin error: ", p, fieldId), err)
ReadFieldError:
	return thrift.PrependError(fmt.Sprintf("%T read field %d '%s' error: ", p, fieldId, fieldIDToName_GetHistoryBulletsResponse[fieldId]), err)
SkipFieldError:
	return thrift.PrependError(fmt.Sprintf("%T field %d skip type %d error: ", p, fieldId, fieldTypeId), err)

ReadFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T read field end error", p), err)
ReadStructEndError:
	return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
}

func (p *GetHistoryBulletsResponse) ReadField1(iprot thrift.TProtocol) error {
	_, size, err := iprot.ReadListBegin()
	if err != nil {
		return err
	}
	_field := make([]*base.Bullet, 0, size)
	values := make([]base.Bullet, size)
	for i := 0; i < size; i++ {
		_elem := &values[i]

		if err := _elem.Read(iprot); err != nil {
			return err
		}

		_field = append(_field, _elem)
	}
	if err := iprot.ReadListEnd(); err != nil {
		return err
	}
	p.Bullets = _field
	return nil
}

func (p *GetHistoryBulletsResponse) Write(oprot thrift.TProtocol) (err error) {
	var fieldId int16
	if err = oprot.WriteStructBegin("GetHistoryBulletsResponse"); err != nil {
		goto WriteStructBeginError
	}
	if p != nil {
		if err = p.writeField1(oprot); err != nil {
			fieldId = 1
			goto WriteFieldError
		}
	}
	if err = oprot.WriteFieldStop(); err != nil {
		goto WriteFieldStopError
	}
	if err = oprot.WriteStructEnd(); err != nil {
		goto WriteStructEndError
	}
	return nil
WriteStructBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
WriteFieldError:
	return thrift.PrependError(fmt.Sprintf("%T write field %d error: ", p, fieldId), err)
WriteFieldStopError:
	return thrift.PrependError(fmt.Sprintf("%T write field stop error: ", p), err)
WriteStructEndError:
	return thrift.PrependError(fmt.Sprintf("%T write struct end error: ", p), err)
}

func (p *GetHistoryBulletsResponse) writeField1(oprot thrift.TProtocol) (err error) {
	if err = oprot.WriteFieldBegin("bullets", thrift.LIST, 1); err != nil {
		goto WriteFieldBeginError
	}
	if err := oprot.WriteListBegin(thrift.STRUCT, len(p.Bullets)); err != nil {
		return err
	}
	for _, v := range p.Bullets {
		if err := v.Write(oprot); err != nil {
			return err
		}
	}
	if err := oprot.WriteListEnd(); err != nil {
		return err
	}
	if err = oprot.WriteFieldEnd(); err != nil {
		goto WriteFieldEndError
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 1 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 1 end error: ", p), err)
}

func (p *GetHistoryBulletsResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetHistoryBulletsResponse(%+v)", *p)

}

func (p *GetHistoryBulletsResponse) DeepEqual(ano *GetHistoryBulletsResponse) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field1DeepEqual(ano.Bullets) {
		return false
	}
	return true
}

func (p *GetHistoryBulletsResponse) Field1DeepEqual(src []*base.Bullet) bool {

	if len(p.Bullets) != len(src) {
		return false
	}
	for i, v := range p.Bullets {
		_src := src[i]
		if !v.DeepEqual(_src) {
			return false
		}
	}
	return true
}

type BulletService interface {
	AddBullet(ctx context.Context, req *AddBulletRequest) (err error)

	GetBullet(ctx context.Context, req *GetBulletRequest) (r *GetBulletResponse, err error)

	GetHistoryBullets(ctx context.Context, req *GetHistoryBulletsRequest) (r *GetHistoryBulletsResponse, err error)
}

type BulletServiceClient struct {
	c thrift.TClient
}

func NewBulletServiceClientFactory(t thrift.TTransport, f thrift.TProtocolFactory) *BulletServiceClient {
	return &BulletServiceClient{
		c: thrift.NewTStandardClient(f.GetProtocol(t), f.GetProtocol(t)),
	}
}

func NewBulletServiceClientProtocol(t thrift.TTransport, iprot thrift.TProtocol, oprot thrift.TProtocol) *BulletServiceClient {
	return &BulletServiceClient{
		c: thrift.NewTStandardClient(iprot, oprot),
	}
}

func NewBulletServiceClient(c thrift.TClient) *BulletServiceClient {
	return &BulletServiceClient{
		c: c,
	}
}

func (p *BulletServiceClient) Client_() thrift.TClient {
	return p.c
}

func (p *BulletServiceClient) AddBullet(ctx context.Context, req *AddBulletRequest) (err error) {
	var _args BulletServiceAddBulletArgs
	_args.Req = req
	var _result BulletServiceAddBulletResult
	if err = p.Client_().Call(ctx, "AddBullet", &_args, &_result); err != nil {
		return
	}
	return nil
}
func (p *BulletServiceClient) GetBullet(ctx context.Context, req *GetBulletRequest) (r *GetBulletResponse, err error) {
	var _args BulletServiceGetBulletArgs
	_args.Req = req
	var _result BulletServiceGetBulletResult
	if err = p.Client_().Call(ctx, "GetBullet", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
func (p *BulletServiceClient) GetHistoryBullets(ctx context.Context, req *GetHistoryBulletsRequest) (r *GetHistoryBulletsResponse, err error) {
	var _args BulletServiceGetHistoryBulletsArgs
	_args.Req = req
	var _result BulletServiceGetHistoryBulletsResult
	if err = p.Client_().Call(ctx, "GetHistoryBullets", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

type BulletServiceProcessor struct {
	processorMap map[string]thrift.TProcessorFunction
	handler      BulletService
}

func (p *BulletServiceProcessor) AddToProcessorMap(key string, processor thrift.TProcessorFunction) {
	p.processorMap[key] = processor
}

func (p *BulletServiceProcessor) GetProcessorFunction(key string) (processor thrift.TProcessorFunction, ok bool) {
	processor, ok = p.processorMap[key]
	return processor, ok
}

func (p *BulletServiceProcessor) ProcessorMap() map[string]thrift.TProcessorFunction {
	return p.processorMap
}

func NewBulletServiceProcessor(handler BulletService) *BulletServiceProcessor {
	self := &BulletServiceProcessor{handler: handler, processorMap: make(map[string]thrift.TProcessorFunction)}
	self.AddToProcessorMap("AddBullet", &bulletServiceProcessorAddBullet{handler: handler})
	self.AddToProcessorMap("GetBullet", &bulletServiceProcessorGetBullet{handler: handler})
	self.AddToProcessorMap("GetHistoryBullets", &bulletServiceProcessorGetHistoryBullets{handler: handler})
	return self
}
func (p *BulletServiceProcessor) Process(ctx context.Context, iprot, oprot thrift.TProtocol) (success bool, err thrift.TException) {
	name, _, seqId, err := iprot.ReadMessageBegin()
	if err != nil {
		return false, err
	}
	if processor, ok := p.GetProcessorFunction(name); ok {
		return processor.Process(ctx, seqId, iprot, oprot)
	}
	iprot.Skip(thrift.STRUCT)
	iprot.ReadMessageEnd()
	x := thrift.NewTApplicationException(thrift.UNKNOWN_METHOD, "Unknown function "+name)
	oprot.WriteMessageBegin(name, thrift.EXCEPTION, seqId)
	x.Write(oprot)
	oprot.WriteMessageEnd()
	oprot.Flush(ctx)
	return false, x
}

type bulletServiceProcessorAddBullet struct {
	handler BulletService
}

func (p *bulletServiceProcessorAddBullet) Process(ctx context.Context, seqId int32, iprot, oprot thrift.TProtocol) (success bool, err thrift.TException) {
	args := BulletServiceAddBulletArgs{}
	if err = args.Read(iprot); err != nil {
		iprot.ReadMessageEnd()
		x := thrift.NewTApplicationException(thrift.PROTOCOL_ERROR, err.Error())
		oprot.WriteMessageBegin("AddBullet", thrift.EXCEPTION, seqId)
		x.Write(oprot)
		oprot.WriteMessageEnd()
		oprot.Flush(ctx)
		return false, err
	}

	iprot.ReadMessageEnd()
	var err2 error
	result := BulletServiceAddBulletResult{}
	if err2 = p.handler.AddBullet(ctx, args.Req); err2 != nil {
		x := thrift.NewTApplicationException(thrift.INTERNAL_ERROR, "Internal error processing AddBullet: "+err2.Error())
		oprot.WriteMessageBegin("AddBullet", thrift.EXCEPTION, seqId)
		x.Write(oprot)
		oprot.WriteMessageEnd()
		oprot.Flush(ctx)
		return true, err2
	}
	if err2 = oprot.WriteMessageBegin("AddBullet", thrift.REPLY, seqId); err2 != nil {
		err = err2
	}
	if err2 = result.Write(oprot); err == nil && err2 != nil {
		err = err2
	}
	if err2 = oprot.WriteMessageEnd(); err == nil && err2 != nil {
		err = err2
	}
	if err2 = oprot.Flush(ctx); err == nil && err2 != nil {
		err = err2
	}
	if err != nil {
		return
	}
	return true, err
}

type bulletServiceProcessorGetBullet struct {
	handler BulletService
}

func (p *bulletServiceProcessorGetBullet) Process(ctx context.Context, seqId int32, iprot, oprot thrift.TProtocol) (success bool, err thrift.TException) {
	args := BulletServiceGetBulletArgs{}
	if err = args.Read(iprot); err != nil {
		iprot.ReadMessageEnd()
		x := thrift.NewTApplicationException(thrift.PROTOCOL_ERROR, err.Error())
		oprot.WriteMessageBegin("GetBullet", thrift.EXCEPTION, seqId)
		x.Write(oprot)
		oprot.WriteMessageEnd()
		oprot.Flush(ctx)
		return false, err
	}

	iprot.ReadMessageEnd()
	var err2 error
	result := BulletServiceGetBulletResult{}
	var retval *GetBulletResponse
	if retval, err2 = p.handler.GetBullet(ctx, args.Req); err2 != nil {
		x := thrift.NewTApplicationException(thrift.INTERNAL_ERROR, "Internal error processing GetBullet: "+err2.Error())
		oprot.WriteMessageBegin("GetBullet", thrift.EXCEPTION, seqId)
		x.Write(oprot)
		oprot.WriteMessageEnd()
		oprot.Flush(ctx)
		return true, err2
	} else {
		result.Success = retval
	}
	if err2 = oprot.WriteMessageBegin("GetBullet", thrift.REPLY, seqId); err2 != nil {
		err = err2
	}
	if err2 = result.Write(oprot); err == nil && err2 != nil {
		err = err2
	}
	if err2 = oprot.WriteMessageEnd(); err == nil && err2 != nil {
		err = err2
	}
	if err2 = oprot.Flush(ctx); err == nil && err2 != nil {
		err = err2
	}
	if err != nil {
		return
	}
	return true, err
}

type bulletServiceProcessorGetHistoryBullets struct {
	handler BulletService
}

func (p *bulletServiceProcessorGetHistoryBullets) Process(ctx context.Context, seqId int32, iprot, oprot thrift.TProtocol) (success bool, err thrift.TException) {
	args := BulletServiceGetHistoryBulletsArgs{}
	if err = args.Read(iprot); err != nil {
		iprot.ReadMessageEnd()
		x := thrift.NewTApplicationException(thrift.PROTOCOL_ERROR, err.Error())
		oprot.WriteMessageBegin("GetHistoryBullets", thrift.EXCEPTION, seqId)
		x.Write(oprot)
		oprot.WriteMessageEnd()
		oprot.Flush(ctx)
		return false, err
	}

	iprot.ReadMessageEnd()
	var err2 error
	result := BulletServiceGetHistoryBulletsResult{}
	var retval *GetHistoryBulletsResponse
	if retval, err2 = p.handler.GetHistoryBullets(ctx, args.Req); err2 != nil {
		x := thrift.NewTApplicationException(thrift.INTERNAL_ERROR, "Internal error processing GetHistoryBullets: "+err2.Error())
		oprot.WriteMessageBegin("GetHistoryBullets", thrift.EXCEPTION, seqId)
		x.Write(oprot)
		oprot.WriteMessageEnd()
		oprot.Flush(ctx)
		return true, err2
	} else {
		result.Success = retval
	}
	if err2 = oprot.WriteMessageBegin("GetHistoryBullets", thrift.REPLY, seqId); err2 != nil {
		err = err2
	}
	if err2 = result.Write(oprot); err == nil && err2 != nil {
		err = err2
	}
	if err2 = oprot.WriteMessageEnd(); err == nil && err2 != nil {
		err = err2
	}
	if err2 = oprot.Flush(ctx); err == nil && err2 != nil {
		err = err2
	}
	if err != nil {
		return
	}
	return true, err
}

type BulletServiceAddBulletArgs struct {
	Req *AddBulletRequest `thrift:"req,1" frugal:"1,default,AddBulletRequest" json:"req"`
}

func NewBulletServiceAddBulletArgs() *BulletServiceAddBulletArgs {
	return &BulletServiceAddBulletArgs{}
}

func (p *BulletServiceAddBulletArgs) InitDefault() {
	*p = BulletServiceAddBulletArgs{}
}

var BulletServiceAddBulletArgs_Req_DEFAULT *AddBulletRequest

func (p *BulletServiceAddBulletArgs) GetReq() (v *AddBulletRequest) {
	if !p.IsSetReq() {
		return BulletServiceAddBulletArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *BulletServiceAddBulletArgs) SetReq(val *AddBulletRequest) {
	p.Req = val
}

var fieldIDToName_BulletServiceAddBulletArgs = map[int16]string{
	1: "req",
}

func (p *BulletServiceAddBulletArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *BulletServiceAddBulletArgs) Read(iprot thrift.TProtocol) (err error) {

	var fieldTypeId thrift.TType
	var fieldId int16

	if _, err = iprot.ReadStructBegin(); err != nil {
		goto ReadStructBeginError
	}

	for {
		_, fieldTypeId, fieldId, err = iprot.ReadFieldBegin()
		if err != nil {
			goto ReadFieldBeginError
		}
		if fieldTypeId == thrift.STOP {
			break
		}

		switch fieldId {
		case 1:
			if fieldTypeId == thrift.STRUCT {
				if err = p.ReadField1(iprot); err != nil {
					goto ReadFieldError
				}
			} else if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		default:
			if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		}
		if err = iprot.ReadFieldEnd(); err != nil {
			goto ReadFieldEndError
		}
	}
	if err = iprot.ReadStructEnd(); err != nil {
		goto ReadStructEndError
	}

	return nil
ReadStructBeginError:
	return thrift.PrependError(fmt.Sprintf("%T read struct begin error: ", p), err)
ReadFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T read field %d begin error: ", p, fieldId), err)
ReadFieldError:
	return thrift.PrependError(fmt.Sprintf("%T read field %d '%s' error: ", p, fieldId, fieldIDToName_BulletServiceAddBulletArgs[fieldId]), err)
SkipFieldError:
	return thrift.PrependError(fmt.Sprintf("%T field %d skip type %d error: ", p, fieldId, fieldTypeId), err)

ReadFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T read field end error", p), err)
ReadStructEndError:
	return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
}

func (p *BulletServiceAddBulletArgs) ReadField1(iprot thrift.TProtocol) error {
	_field := NewAddBulletRequest()
	if err := _field.Read(iprot); err != nil {
		return err
	}
	p.Req = _field
	return nil
}

func (p *BulletServiceAddBulletArgs) Write(oprot thrift.TProtocol) (err error) {
	var fieldId int16
	if err = oprot.WriteStructBegin("AddBullet_args"); err != nil {
		goto WriteStructBeginError
	}
	if p != nil {
		if err = p.writeField1(oprot); err != nil {
			fieldId = 1
			goto WriteFieldError
		}
	}
	if err = oprot.WriteFieldStop(); err != nil {
		goto WriteFieldStopError
	}
	if err = oprot.WriteStructEnd(); err != nil {
		goto WriteStructEndError
	}
	return nil
WriteStructBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
WriteFieldError:
	return thrift.PrependError(fmt.Sprintf("%T write field %d error: ", p, fieldId), err)
WriteFieldStopError:
	return thrift.PrependError(fmt.Sprintf("%T write field stop error: ", p), err)
WriteStructEndError:
	return thrift.PrependError(fmt.Sprintf("%T write struct end error: ", p), err)
}

func (p *BulletServiceAddBulletArgs) writeField1(oprot thrift.TProtocol) (err error) {
	if err = oprot.WriteFieldBegin("req", thrift.STRUCT, 1); err != nil {
		goto WriteFieldBeginError
	}
	if err := p.Req.Write(oprot); err != nil {
		return err
	}
	if err = oprot.WriteFieldEnd(); err != nil {
		goto WriteFieldEndError
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 1 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 1 end error: ", p), err)
}

func (p *BulletServiceAddBulletArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("BulletServiceAddBulletArgs(%+v)", *p)

}

func (p *BulletServiceAddBulletArgs) DeepEqual(ano *BulletServiceAddBulletArgs) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field1DeepEqual(ano.Req) {
		return false
	}
	return true
}

func (p *BulletServiceAddBulletArgs) Field1DeepEqual(src *AddBulletRequest) bool {

	if !p.Req.DeepEqual(src) {
		return false
	}
	return true
}

type BulletServiceAddBulletResult struct {
}

func NewBulletServiceAddBulletResult() *BulletServiceAddBulletResult {
	return &BulletServiceAddBulletResult{}
}

func (p *BulletServiceAddBulletResult) InitDefault() {
	*p = BulletServiceAddBulletResult{}
}

var fieldIDToName_BulletServiceAddBulletResult = map[int16]string{}

func (p *BulletServiceAddBulletResult) Read(iprot thrift.TProtocol) (err error) {

	var fieldTypeId thrift.TType
	var fieldId int16

	if _, err = iprot.ReadStructBegin(); err != nil {
		goto ReadStructBeginError
	}

	for {
		_, fieldTypeId, fieldId, err = iprot.ReadFieldBegin()
		if err != nil {
			goto ReadFieldBeginError
		}
		if fieldTypeId == thrift.STOP {
			break
		}
		if err = iprot.Skip(fieldTypeId); err != nil {
			goto SkipFieldTypeError
		}
		if err = iprot.ReadFieldEnd(); err != nil {
			goto ReadFieldEndError
		}
	}
	if err = iprot.ReadStructEnd(); err != nil {
		goto ReadStructEndError
	}

	return nil
ReadStructBeginError:
	return thrift.PrependError(fmt.Sprintf("%T read struct begin error: ", p), err)
ReadFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T read field %d begin error: ", p, fieldId), err)
SkipFieldTypeError:
	return thrift.PrependError(fmt.Sprintf("%T skip field type %d error", p, fieldTypeId), err)

ReadFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T read field end error", p), err)
ReadStructEndError:
	return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
}

func (p *BulletServiceAddBulletResult) Write(oprot thrift.TProtocol) (err error) {
	if err = oprot.WriteStructBegin("AddBullet_result"); err != nil {
		goto WriteStructBeginError
	}
	if p != nil {
	}
	if err = oprot.WriteFieldStop(); err != nil {
		goto WriteFieldStopError
	}
	if err = oprot.WriteStructEnd(); err != nil {
		goto WriteStructEndError
	}
	return nil
WriteStructBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
WriteFieldStopError:
	return thrift.PrependError(fmt.Sprintf("%T write field stop error: ", p), err)
WriteStructEndError:
	return thrift.PrependError(fmt.Sprintf("%T write struct end error: ", p), err)
}

func (p *BulletServiceAddBulletResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("BulletServiceAddBulletResult(%+v)", *p)

}

func (p *BulletServiceAddBulletResult) DeepEqual(ano *BulletServiceAddBulletResult) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	return true
}

type BulletServiceGetBulletArgs struct {
	Req *GetBulletRequest `thrift:"req,1" frugal:"1,default,GetBulletRequest" json:"req"`
}

func NewBulletServiceGetBulletArgs() *BulletServiceGetBulletArgs {
	return &BulletServiceGetBulletArgs{}
}

func (p *BulletServiceGetBulletArgs) InitDefault() {
	*p = BulletServiceGetBulletArgs{}
}

var BulletServiceGetBulletArgs_Req_DEFAULT *GetBulletRequest

func (p *BulletServiceGetBulletArgs) GetReq() (v *GetBulletRequest) {
	if !p.IsSetReq() {
		return BulletServiceGetBulletArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *BulletServiceGetBulletArgs) SetReq(val *GetBulletRequest) {
	p.Req = val
}

var fieldIDToName_BulletServiceGetBulletArgs = map[int16]string{
	1: "req",
}

func (p *BulletServiceGetBulletArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *BulletServiceGetBulletArgs) Read(iprot thrift.TProtocol) (err error) {

	var fieldTypeId thrift.TType
	var fieldId int16

	if _, err = iprot.ReadStructBegin(); err != nil {
		goto ReadStructBeginError
	}

	for {
		_, fieldTypeId, fieldId, err = iprot.ReadFieldBegin()
		if err != nil {
			goto ReadFieldBeginError
		}
		if fieldTypeId == thrift.STOP {
			break
		}

		switch fieldId {
		case 1:
			if fieldTypeId == thrift.STRUCT {
				if err = p.ReadField1(iprot); err != nil {
					goto ReadFieldError
				}
			} else if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		default:
			if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		}
		if err = iprot.ReadFieldEnd(); err != nil {
			goto ReadFieldEndError
		}
	}
	if err = iprot.ReadStructEnd(); err != nil {
		goto ReadStructEndError
	}

	return nil
ReadStructBeginError:
	return thrift.PrependError(fmt.Sprintf("%T read struct begin error: ", p), err)
ReadFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T read field %d begin error: ", p, fieldId), err)
ReadFieldError:
	return thrift.PrependError(fmt.Sprintf("%T read field %d '%s' error: ", p, fieldId, fieldIDToName_BulletServiceGetBulletArgs[fieldId]), err)
SkipFieldError:
	return thrift.PrependError(fmt.Sprintf("%T field %d skip type %d error: ", p, fieldId, fieldTypeId), err)

ReadFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T read field end error", p), err)
ReadStructEndError:
	return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
}

func (p *BulletServiceGetBulletArgs) ReadField1(iprot thrift.TProtocol) error {
	_field := NewGetBulletRequest()
	if err := _field.Read(iprot); err != nil {
		return err
	}
	p.Req = _field
	return nil
}

func (p *BulletServiceGetBulletArgs) Write(oprot thrift.TProtocol) (err error) {
	var fieldId int16
	if err = oprot.WriteStructBegin("GetBullet_args"); err != nil {
		goto WriteStructBeginError
	}
	if p != nil {
		if err = p.writeField1(oprot); err != nil {
			fieldId = 1
			goto WriteFieldError
		}
	}
	if err = oprot.WriteFieldStop(); err != nil {
		goto WriteFieldStopError
	}
	if err = oprot.WriteStructEnd(); err != nil {
		goto WriteStructEndError
	}
	return nil
WriteStructBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
WriteFieldError:
	return thrift.PrependError(fmt.Sprintf("%T write field %d error: ", p, fieldId), err)
WriteFieldStopError:
	return thrift.PrependError(fmt.Sprintf("%T write field stop error: ", p), err)
WriteStructEndError:
	return thrift.PrependError(fmt.Sprintf("%T write struct end error: ", p), err)
}

func (p *BulletServiceGetBulletArgs) writeField1(oprot thrift.TProtocol) (err error) {
	if err = oprot.WriteFieldBegin("req", thrift.STRUCT, 1); err != nil {
		goto WriteFieldBeginError
	}
	if err := p.Req.Write(oprot); err != nil {
		return err
	}
	if err = oprot.WriteFieldEnd(); err != nil {
		goto WriteFieldEndError
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 1 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 1 end error: ", p), err)
}

func (p *BulletServiceGetBulletArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("BulletServiceGetBulletArgs(%+v)", *p)

}

func (p *BulletServiceGetBulletArgs) DeepEqual(ano *BulletServiceGetBulletArgs) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field1DeepEqual(ano.Req) {
		return false
	}
	return true
}

func (p *BulletServiceGetBulletArgs) Field1DeepEqual(src *GetBulletRequest) bool {

	if !p.Req.DeepEqual(src) {
		return false
	}
	return true
}

type BulletServiceGetBulletResult struct {
	Success *GetBulletResponse `thrift:"success,0,optional" frugal:"0,optional,GetBulletResponse" json:"success,omitempty"`
}

func NewBulletServiceGetBulletResult() *BulletServiceGetBulletResult {
	return &BulletServiceGetBulletResult{}
}

func (p *BulletServiceGetBulletResult) InitDefault() {
	*p = BulletServiceGetBulletResult{}
}

var BulletServiceGetBulletResult_Success_DEFAULT *GetBulletResponse

func (p *BulletServiceGetBulletResult) GetSuccess() (v *GetBulletResponse) {
	if !p.IsSetSuccess() {
		return BulletServiceGetBulletResult_Success_DEFAULT
	}
	return p.Success
}
func (p *BulletServiceGetBulletResult) SetSuccess(x interface{}) {
	p.Success = x.(*GetBulletResponse)
}

var fieldIDToName_BulletServiceGetBulletResult = map[int16]string{
	0: "success",
}

func (p *BulletServiceGetBulletResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *BulletServiceGetBulletResult) Read(iprot thrift.TProtocol) (err error) {

	var fieldTypeId thrift.TType
	var fieldId int16

	if _, err = iprot.ReadStructBegin(); err != nil {
		goto ReadStructBeginError
	}

	for {
		_, fieldTypeId, fieldId, err = iprot.ReadFieldBegin()
		if err != nil {
			goto ReadFieldBeginError
		}
		if fieldTypeId == thrift.STOP {
			break
		}

		switch fieldId {
		case 0:
			if fieldTypeId == thrift.STRUCT {
				if err = p.ReadField0(iprot); err != nil {
					goto ReadFieldError
				}
			} else if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		default:
			if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		}
		if err = iprot.ReadFieldEnd(); err != nil {
			goto ReadFieldEndError
		}
	}
	if err = iprot.ReadStructEnd(); err != nil {
		goto ReadStructEndError
	}

	return nil
ReadStructBeginError:
	return thrift.PrependError(fmt.Sprintf("%T read struct begin error: ", p), err)
ReadFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T read field %d begin error: ", p, fieldId), err)
ReadFieldError:
	return thrift.PrependError(fmt.Sprintf("%T read field %d '%s' error: ", p, fieldId, fieldIDToName_BulletServiceGetBulletResult[fieldId]), err)
SkipFieldError:
	return thrift.PrependError(fmt.Sprintf("%T field %d skip type %d error: ", p, fieldId, fieldTypeId), err)

ReadFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T read field end error", p), err)
ReadStructEndError:
	return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
}

func (p *BulletServiceGetBulletResult) ReadField0(iprot thrift.TProtocol) error {
	_field := NewGetBulletResponse()
	if err := _field.Read(iprot); err != nil {
		return err
	}
	p.Success = _field
	return nil
}

func (p *BulletServiceGetBulletResult) Write(oprot thrift.TProtocol) (err error) {
	var fieldId int16
	if err = oprot.WriteStructBegin("GetBullet_result"); err != nil {
		goto WriteStructBeginError
	}
	if p != nil {
		if err = p.writeField0(oprot); err != nil {
			fieldId = 0
			goto WriteFieldError
		}
	}
	if err = oprot.WriteFieldStop(); err != nil {
		goto WriteFieldStopError
	}
	if err = oprot.WriteStructEnd(); err != nil {
		goto WriteStructEndError
	}
	return nil
WriteStructBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
WriteFieldError:
	return thrift.PrependError(fmt.Sprintf("%T write field %d error: ", p, fieldId), err)
WriteFieldStopError:
	return thrift.PrependError(fmt.Sprintf("%T write field stop error: ", p), err)
WriteStructEndError:
	return thrift.PrependError(fmt.Sprintf("%T write struct end error: ", p), err)
}

func (p *BulletServiceGetBulletResult) writeField0(oprot thrift.TProtocol) (err error) {
	if p.IsSetSuccess() {
		if err = oprot.WriteFieldBegin("success", thrift.STRUCT, 0); err != nil {
			goto WriteFieldBeginError
		}
		if err := p.Success.Write(oprot); err != nil {
			return err
		}
		if err = oprot.WriteFieldEnd(); err != nil {
			goto WriteFieldEndError
		}
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 0 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 0 end error: ", p), err)
}

func (p *BulletServiceGetBulletResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("BulletServiceGetBulletResult(%+v)", *p)

}

func (p *BulletServiceGetBulletResult) DeepEqual(ano *BulletServiceGetBulletResult) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field0DeepEqual(ano.Success) {
		return false
	}
	return true
}

func (p *BulletServiceGetBulletResult) Field0DeepEqual(src *GetBulletResponse) bool {

	if !p.Success.DeepEqual(src) {
		return false
	}
	return true
}

type BulletServiceGetHistoryBulletsArgs struct {
	Req *GetHistoryBulletsRequest `thrift:"req,1" frugal:"1,default,GetHistoryBulletsRequest" json:"req"`
}

func NewBulletServiceGetHistoryBulletsArgs() *BulletServiceGetHistoryBulletsArgs {
	return &BulletServiceGetHistoryBulletsArgs{}
}

func (p *BulletServiceGetHistoryBulletsArgs) InitDefault() {
	*p = BulletServiceGetHistoryBulletsArgs{}
}

var BulletServiceGetHistoryBulletsArgs_Req_DEFAULT *GetHistoryBulletsRequest

func (p *BulletServiceGetHistoryBulletsArgs) GetReq() (v *GetHistoryBulletsRequest) {
	if !p.IsSetReq() {
		return BulletServiceGetHistoryBulletsArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *BulletServiceGetHistoryBulletsArgs) SetReq(val *GetHistoryBulletsRequest) {
	p.Req = val
}

var fieldIDToName_BulletServiceGetHistoryBulletsArgs = map[int16]string{
	1: "req",
}

func (p *BulletServiceGetHistoryBulletsArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *BulletServiceGetHistoryBulletsArgs) Read(iprot thrift.TProtocol) (err error) {

	var fieldTypeId thrift.TType
	var fieldId int16

	if _, err = iprot.ReadStructBegin(); err != nil {
		goto ReadStructBeginError
	}

	for {
		_, fieldTypeId, fieldId, err = iprot.ReadFieldBegin()
		if err != nil {
			goto ReadFieldBeginError
		}
		if fieldTypeId == thrift.STOP {
			break
		}

		switch fieldId {
		case 1:
			if fieldTypeId == thrift.STRUCT {
				if err = p.ReadField1(iprot); err != nil {
					goto ReadFieldError
				}
			} else if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		default:
			if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		}
		if err = iprot.ReadFieldEnd(); err != nil {
			goto ReadFieldEndError
		}
	}
	if err = iprot.ReadStructEnd(); err != nil {
		goto ReadStructEndError
	}

	return nil
ReadStructBeginError:
	return thrift.PrependError(fmt.Sprintf("%T read struct begin error: ", p), err)
ReadFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T read field %d begin error: ", p, fieldId), err)
ReadFieldError:
	return thrift.PrependError(fmt.Sprintf("%T read field %d '%s' error: ", p, fieldId, fieldIDToName_BulletServiceGetHistoryBulletsArgs[fieldId]), err)
SkipFieldError:
	return thrift.PrependError(fmt.Sprintf("%T field %d skip type %d error: ", p, fieldId, fieldTypeId), err)

ReadFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T read field end error", p), err)
ReadStructEndError:
	return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
}

func (p *BulletServiceGetHistoryBulletsArgs) ReadField1(iprot thrift.TProtocol) error {
	_field := NewGetHistoryBulletsRequest()
	if err := _field.Read(iprot); err != nil {
		return err
	}
	p.Req = _field
	return nil
}

func (p *BulletServiceGetHistoryBulletsArgs) Write(oprot thrift.TProtocol) (err error) {
	var fieldId int16
	if err = oprot.WriteStructBegin("GetHistoryBullets_args"); err != nil {
		goto WriteStructBeginError
	}
	if p != nil {
		if err = p.writeField1(oprot); err != nil {
			fieldId = 1
			goto WriteFieldError
		}
	}
	if err = oprot.WriteFieldStop(); err != nil {
		goto WriteFieldStopError
	}
	if err = oprot.WriteStructEnd(); err != nil {
		goto WriteStructEndError
	}
	return nil
WriteStructBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
WriteFieldError:
	return thrift.PrependError(fmt.Sprintf("%T write field %d error: ", p, fieldId), err)
WriteFieldStopError:
	return thrift.PrependError(fmt.Sprintf("%T write field stop error: ", p), err)
WriteStructEndError:
	return thrift.PrependError(fmt.Sprintf("%T write struct end error: ", p), err)
}

func (p *BulletServiceGetHistoryBulletsArgs) writeField1(oprot thrift.TProtocol) (err error) {
	if err = oprot.WriteFieldBegin("req", thrift.STRUCT, 1); err != nil {
		goto WriteFieldBeginError
	}
	if err := p.Req.Write(oprot); err != nil {
		return err
	}
	if err = oprot.WriteFieldEnd(); err != nil {
		goto WriteFieldEndError
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 1 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 1 end error: ", p), err)
}

func (p *BulletServiceGetHistoryBulletsArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("BulletServiceGetHistoryBulletsArgs(%+v)", *p)

}

func (p *BulletServiceGetHistoryBulletsArgs) DeepEqual(ano *BulletServiceGetHistoryBulletsArgs) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field1DeepEqual(ano.Req) {
		return false
	}
	return true
}

func (p *BulletServiceGetHistoryBulletsArgs) Field1DeepEqual(src *GetHistoryBulletsRequest) bool {

	if !p.Req.DeepEqual(src) {
		return false
	}
	return true
}

type BulletServiceGetHistoryBulletsResult struct {
	Success *GetHistoryBulletsResponse `thrift:"success,0,optional" frugal:"0,optional,GetHistoryBulletsResponse" json:"success,omitempty"`
}

func NewBulletServiceGetHistoryBulletsResult() *BulletServiceGetHistoryBulletsResult {
	return &BulletServiceGetHistoryBulletsResult{}
}

func (p *BulletServiceGetHistoryBulletsResult) InitDefault() {
	*p = BulletServiceGetHistoryBulletsResult{}
}

var BulletServiceGetHistoryBulletsResult_Success_DEFAULT *GetHistoryBulletsResponse

func (p *BulletServiceGetHistoryBulletsResult) GetSuccess() (v *GetHistoryBulletsResponse) {
	if !p.IsSetSuccess() {
		return BulletServiceGetHistoryBulletsResult_Success_DEFAULT
	}
	return p.Success
}
func (p *BulletServiceGetHistoryBulletsResult) SetSuccess(x interface{}) {
	p.Success = x.(*GetHistoryBulletsResponse)
}

var fieldIDToName_BulletServiceGetHistoryBulletsResult = map[int16]string{
	0: "success",
}

func (p *BulletServiceGetHistoryBulletsResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *BulletServiceGetHistoryBulletsResult) Read(iprot thrift.TProtocol) (err error) {

	var fieldTypeId thrift.TType
	var fieldId int16

	if _, err = iprot.ReadStructBegin(); err != nil {
		goto ReadStructBeginError
	}

	for {
		_, fieldTypeId, fieldId, err = iprot.ReadFieldBegin()
		if err != nil {
			goto ReadFieldBeginError
		}
		if fieldTypeId == thrift.STOP {
			break
		}

		switch fieldId {
		case 0:
			if fieldTypeId == thrift.STRUCT {
				if err = p.ReadField0(iprot); err != nil {
					goto ReadFieldError
				}
			} else if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		default:
			if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		}
		if err = iprot.ReadFieldEnd(); err != nil {
			goto ReadFieldEndError
		}
	}
	if err = iprot.ReadStructEnd(); err != nil {
		goto ReadStructEndError
	}

	return nil
ReadStructBeginError:
	return thrift.PrependError(fmt.Sprintf("%T read struct begin error: ", p), err)
ReadFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T read field %d begin error: ", p, fieldId), err)
ReadFieldError:
	return thrift.PrependError(fmt.Sprintf("%T read field %d '%s' error: ", p, fieldId, fieldIDToName_BulletServiceGetHistoryBulletsResult[fieldId]), err)
SkipFieldError:
	return thrift.PrependError(fmt.Sprintf("%T field %d skip type %d error: ", p, fieldId, fieldTypeId), err)

ReadFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T read field end error", p), err)
ReadStructEndError:
	return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
}

func (p *BulletServiceGetHistoryBulletsResult) ReadField0(iprot thrift.TProtocol) error {
	_field := NewGetHistoryBulletsResponse()
	if err := _field.Read(iprot); err != nil {
		return err
	}
	p.Success = _field
	return nil
}

func (p *BulletServiceGetHistoryBulletsResult) Write(oprot thrift.TProtocol) (err error) {
	var fieldId int16
	if err = oprot.WriteStructBegin("GetHistoryBullets_result"); err != nil {
		goto WriteStructBeginError
	}
	if p != nil {
		if err = p.writeField0(oprot); err != nil {
			fieldId = 0
			goto WriteFieldError
		}
	}
	if err = oprot.WriteFieldStop(); err != nil {
		goto WriteFieldStopError
	}
	if err = oprot.WriteStructEnd(); err != nil {
		goto WriteStructEndError
	}
	return nil
WriteStructBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
WriteFieldError:
	return thrift.PrependError(fmt.Sprintf("%T write field %d error: ", p, fieldId), err)
WriteFieldStopError:
	return thrift.PrependError(fmt.Sprintf("%T write field stop error: ", p), err)
WriteStructEndError:
	return thrift.PrependError(fmt.Sprintf("%T write struct end error: ", p), err)
}

func (p *BulletServiceGetHistoryBulletsResult) writeField0(oprot thrift.TProtocol) (err error) {
	if p.IsSetSuccess() {
		if err = oprot.WriteFieldBegin("success", thrift.STRUCT, 0); err != nil {
			goto WriteFieldBeginError
		}
		if err := p.Success.Write(oprot); err != nil {
			return err
		}
		if err = oprot.WriteFieldEnd(); err != nil {
			goto WriteFieldEndError
		}
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 0 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 0 end error: ", p), err)
}

func (p *BulletServiceGetHistoryBulletsResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("BulletServiceGetHistoryBulletsResult(%+v)", *p)

}

func (p *BulletServiceGetHistoryBulletsResult) DeepEqual(ano *BulletServiceGetHistoryBulletsResult) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field0DeepEqual(ano.Success) {
		return false
	}
	return true
}

func (p *BulletServiceGetHistoryBulletsResult) Field0DeepEqual(src *GetHistoryBulletsResponse) bool {

	if !p.Success.DeepEqual(src) {
		return false
	}
	return true
}
